---

# This playbook will install the prerequisite packages for setting up backup and alert management scripts.
# Amazon Time Sync Service : https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/
# AWS SSM Client installation : https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html
# AWS CLI installation : https://docs.aws.amazon.com/cli/latest/userguide/installing.html
# version 1.0 last modified date: Jul 06, 2018.

- name: test playbook
  hosts: 127.0.0.1
  become: yes
  tasks:
  - name: remove ntp clients
    yum: name=ntp* state=absent
   
  - name: install chrony
    yum: name=chrony state=present
  
  - name: start chrony service
    service: name=chronyd state=started enabled=yes
  
  - name: install epel repository
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present   
 
  - name: install python
    yum: name="{{item}}" state=latest
    with_items:
    - python
    - python-pip
  
  - name: install aws cli
    pip: name=awscli state=latest
  
  - name: instal aws ssm
    yum: name=https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm state=present

  - name: start ssm service
    systemd: name=amazon-ssm-agent state=started 
